DETAILS.update({
    'kq074': 'An adult female sheep is not called the same thing as a young sheep or a male.',
    'kq075': 'An adult male sheep kept for breeding has a specific name.',
    'kq076': 'A young bovine has a common name used on NZ farms before it is a cow or bull.',
    'kq077': 'Colostrum is the first milk. Newborn lambs and calves need it for antibodies.',
    'kq078': 'Ruminants have a specialised stomach system and chew the cud.',
    'kq079': 'A broody hen wants to sit on eggs and hatch them.',
    'kq080': 'Biosecurity with poultry means stopping disease moving on boots, boxes and birds.',
    'kq081': 'Shearing is taking the wool off sheep.',
    'kq082': 'Dags are dirty clumps of wool around a sheep rear.',
    'kq083': 'A steer is a castrated male raised for beef.',
    'kq084': 'Layer hens are kept mainly to produce eggs.',
    'kq085': 'Broiler chickens are raised mainly for meat.',
    'kq086': 'Where used, docking or tailing lambs is about cleanliness and reducing flystrike risk.',
    'kq087': 'Flystrike is a serious summer welfare problem when flies lay eggs in damp wool or wounds.',
    'kq088': 'A weaner calf has been taken off milk and is eating solid feed.',
    'kq089': 'Birds need a safe house at night to keep them from predators and weather.',
    'kq090': 'Chickens swallow grit so the gizzard can grind grain.',
    'kq091': 'In NZ a hogget is a young sheep between lamb and fully adult mutton age.',
    'kq092': 'Dairy calves on NZ farms are commonly reared on milk then weaned onto grass and meal.',
    'kq093': 'A house deck is an outdoor timber platform attached to or beside the house.',
    'kq094': 'NZS 3604 is the everyday timber-house standard many deck builders follow for sizes and fixings.',
    'kq095': 'Timber in the ground needs a higher treatment level than timber that stays dry in the air.',
    'kq096': 'Joists and bearers above ground still need a treatment level suited to outdoor moisture.',
    'kq097': 'Joists are the repeated framing members that carry the decking boards.',
    'kq098': 'Bearers sit under the joists and carry them to the piles.',
    'kq099': 'Piles are the posts in the ground that hold the deck up.',
    'kq100': 'Decking boards are the walking surface. They need a gap so water can drain.',
    'kq101': 'A ledger is the timber fixed back to the house that the deck framing can land on.',
    'kq102': 'Stringers or similar members carry stair treads on a deck stair.',
    'kq103': 'Barrier height at the edge of a raised deck is set so people are less likely to fall.',
    'kq104': 'A fall height of a metre or more is when barriers become a serious code issue.',
    'kq105': 'H3.2 is a common above-ground outdoor treatment level; in-ground needs more.',
    'kq106': 'Connections should use outdoor-rated fixings so they do not rust out.',
    'kq107': 'A cantilever is where joists or bearers stick out past the last support.',
    'kq108': 'Stairs need consistent rise and going so people do not trip.',
    'kq109': 'Openings in a barrier must be small enough that a child cannot slip through.',
    'kq110': 'Balustrade is another word for the edge barrier and its infill.',
    'kq111': 'Outdoor fixings should be galvanised or stainless so they survive weather.',
    'kq112': 'Joist spacing must match the decking span or the boards will bounce and fail.',
    'kq113': 'A pile footing is usually concrete in the ground so the post does not sink.',
    'kq114': 'A stair handrail is to hold while you climb; an edge barrier stops a fall from the deck.',
    'kq115': 'Councils may require a building consent depending on height and size. Check before you build.',
    'kq116': 'Turkiye is the country official name in Turkish. English still widely uses another country name.',
    'kq117': 'Turkey capital is not its largest city. Name the political capital in the centre of the country.',
    'kq118': 'The biggest city sits on the Bosporus and is not the capital.',
    'kq119': 'Istanbul is famous for sitting on two continents at once.',
    'kq120': 'The Bosphorus is the strait that links the Black Sea to the Sea of Marmara.',
    'kq121': 'Most of Turkey land is the large Asian peninsula, not the small European slice.',
    'kq122': 'The Republic replaced the Ottoman Empire in the early 1920s.',
    'kq123': 'Ataturk is the founder and first president of the Republic of Turkey.',
    'kq124': 'The sea on Turkey north coast is the Black Sea.',
    'kq125': 'The south coast faces the Mediterranean.',
    'kq126': 'The official language used in government and schools is Turkish.',
    'kq127': 'Agri Dagi / Mount Ararat stands in the far east of the country.',
    'kq128': 'Cappadocia is known for fairy chimneys, cave churches and balloon flights.',
    'kq129': 'Ephesus is a great ruined Greco-Roman city on the Aegean side.',
    'kq130': 'The Ottoman capital for centuries was the city on the Bosporus, not the later republic capital.',
    'kq131': 'Turkey is transcontinental because a small part sits in Europe and most sits in Asia.',
    'kq132': 'The Aegean Sea lies between western Turkey and Greece.',
    'kq133': 'The lira is Turkey currency.',
    'kq134': 'Hagia Sophia in Istanbul has been a church, a mosque and a museum at different times.',
    'kq135': 'Anatolia is the large Asian peninsula that makes up most of Turkey land.',
    'kq136': 'One listed country does not actually share a land border with Turkey. Use a map.',
    'kq137': 'Pamukkale is famous for white travertine terraces and warm mineral water.',
    'kq138': 'The national football team is widely associated with red and white.',
    'mc001': 'NZAC is the main professional association for counsellors in Aotearoa New Zealand. Expand the letters.',
    'mc002': 'Unlike doctors, counselling in NZ is not currently run by a state registration board. Many practitioners join a professional body instead.',
    'mc003': 'The NZAC Code lists several named core values. Pick the one that is actually on that list.',
    'mc004': 'Count the named core values in the current NZAC Code of Ethics, not extra good ideas.',
    'mc005': 'One NZAC principle is about honouring Te Tiriti o Waitangi in counselling practice.',
    'mc006': 'Informed consent means clients understand enough about the work, fees, limits and choices to agree freely.',
    'mc007': 'NZAC expects fees to be talked about clearly, not hidden or sprung as a surprise.',
    'mc008': 'A contract can cover fees, times, confidentiality limits and how the work will run.',
    'mc009': 'Competence means staying inside the work you are trained and safe to do, and referring on when you are not.',
    'mc010': 'Confidentiality is the usual rule, but it can be limited when there is serious risk of harm.',
    'mc011': 'NZAC membership usually begins at a provisional / Teina stage before full membership.',
    'mc012': 'A recognised pathway typically includes an approved qualification plus supervised practice hours.',
    'mc013': 'Dual relationships can confuse power and harm the client, so boundaries matter.',
    'mc014': 'Notes should be accurate, secure and kept only as long as good practice and law require.',
    'mc015': 'Non-maleficence means taking care not to make things worse, including knowing when to stop or refer.',
    'mc016': 'Autonomy means supporting the client right to make their own informed choices.',
    'mc017': 'Social justice points counsellors toward fairness, access and attention to wider inequities.',
    'mc018': 'When counselling does not help as hoped, honest review and options including referral are part of ethics.',
    'mc019': 'Respect for colleagues is written into professional behaviour, not an optional extra.',
    'mc020': 'An ethical stuck point is a reason to use supervision and the Code, not to guess alone.',
    'mc021': 'The Code is there to guide members practice and protect the public, not to decorate a website.',
    'mc022': 'Expanding client choice links to autonomy and justice, not to selling extra sessions.',
    'mc023': 'Give the common English name of Te Tiriti o Waitangi.',
    'mc024': 'Health and counselling teaching often names three Treaty-related principles that start with P.',
    'mc025': 'Tangata whenua refers to the people of the land, Maori as indigenous to Aotearoa.',
    'mc026': 'Whanau in helping work often means family in a wide sense, not only two parents and children.',
    'mc027': 'Cultural competence here means being able to work respectfully with Maori and other cultures in Aotearoa.',
    'mc028': 'Mana-enhancing practice aims to strengthen a person dignity and standing, not strip it.',
    'mc029': 'Kaupapa Maori approaches are grounded in Maori values and ways of knowing, not copied-over US models only.',
    'mc030': 'Colonisation still shapes health, land, language and trust, so it belongs in counselling thinking here.',
    'mc031': 'Whakawhanaungatanga is about making genuine relationship and connection before diving into the problem.',
    'mc032': 'Hapu and iwi are sub-tribe and tribe levels of Maori social organisation.',
    'mc033': 'A multicultural stance in NZ education means more than one culture is present and none is treated as the only normal.',
    'mc034': 'Equity means people may need different support to have a fair chance, not identical treatment that ignores history.',
    'mc035': 'The counsellor holds more power in the room. That power needs to be noticed so it is not misused.',
    'mc036': 'NZAC education standards expect Te Tiriti-informed learning in approved programmes.',
    'mc037': 'A noho marae is a stay on a marae as part of learning, not a tourist photo stop.',
    'mc038': 'Using te reo greetings respectfully can be part of culturally safe practice when it is genuine, not mocking.',
    'mc039': 'Protection as a Treaty-related idea in helping is about safeguarding Maori rights, taonga and wellbeing.',
})
