DETAILS.update({
    'hq105': 'The Akhal-Teke is a slim desert-bred horse, often noted for a metallic sheen.',
    'hq106': 'Haflingers are usually small chestnut horses with pale manes, from the Alps.',
    'hq107': 'Morgans are a versatile American breed known for strength in a compact frame.',
    'hq108': 'Icelandic horses are famous for extra gaits such as tolt, as well as toughness.',
    'hq109': 'Lipizzaners are the white horses long linked with the Spanish Riding School in Vienna.',
    'hq110': 'Mustangs are free-roaming horses of North America with mixed historic origins.',
    'hq111': 'A Connemara is an Irish pony or sport pony breed, known as a jumper and all-rounder.',
    'hq112': 'Hotblood usually means the finer, hotter-tempered racing and oriental types such as Thoroughbreds and Arabians.',
    'hq113': 'The Dutch Warmblood (KWPN) is a major sport-horse studbook in dressage and jumping.',
    'hq114': 'Paints are known for bold white-and-colour coat patterns over a stock-horse build.',
    'hq115': 'Welsh ponies are split into sections by size and type. Section A is the mountain-pony end of that scale.',
    'hq116': 'When riders work both ways, a common courtesy is to pass left-to-left, or follow the barn posted rule.',
    'hq117': 'Call your line if you need to pass, so other riders are not surprised.',
    'hq118': 'Many dressage tests start by entering at A and halting at X to salute.',
    'hq119': 'Knocking a rail in jumping is a set number of faults, not a style mark.',
    'hq120': 'A fall of horse or rider in many jumping rounds means elimination from that round.',
    'hq121': 'On eventing cross-country, taking a fence on the wrong side of a flag can mean elimination or a big penalty.',
    'hq122': 'The dressage salute is part of the formal start and end of a test.',
    'hq123': 'Helmet rules at competitions are written for safety and are not optional fashion.',
    'hq124': 'Polo players change horses between periods because the work is intense.',
    'hq125': 'Endurance vet gates check the horse is fit to continue, not just the clock.',
    'hq126': 'Hors concours means competing out of the prizes, for experience, not the official result.',
    'hq127': 'Pick up manure in a shared school so the next horse is not stepping through it.',
    'hq128': 'Racing weighs the rider and gear so assigned weights are actually carried.',
    'hq129': 'A red flag or stop signal on cross-country means stop now, not keep galloping.',
    'hq130': 'Borrowing a horse or tack needs the owner clear permission.',
    'hq131': 'Whip and spur rules at schooling shows are written in the schedule. Check before you ride.',
    'hq132': 'Vaulting freestyle is judged on performance and artistic content, not a racing time.',
    'hq133': 'A clear jumping round means no jumping or time faults in that round.',
    'hq134': 'If a horse is loose in warm-up, stop and help catch it safely instead of adding chaos.',
    'hq135': 'In a crowded aisle, hand-walk with space and warning so nobody gets trapped.',
    'kq001': 'WATL is the main North American-style competitive axe-throwing league. Expand each letter.',
    'kq002': 'A standard WATL game has a set number of throws each before any sudden-death throws if the score is tied.',
    'kq003': 'WATL uses touch scoring. The very centre circle is worth more than the next ring.',
    'kq004': 'A killshot is a special high-value target. It usually has to be called before the throw and hit in the right spot.',
    'kq005': 'If the axe does not stay in the wood until it is scored, that throw is generally worth nothing.',
    'kq006': 'IATF is a different international rule set from WATL. Ring values are not always the same.',
    'kq007': 'IATF Clutch is a named late-game shot. It is only allowed on certain throws, not every throw of the match.',
    'kq008': 'The fault line is the thrower line. Crossing it before scoring is finished can cancel the throw.',
    'kq009': 'Never throw while a person is down-range or the lane is not clear.',
    'kq010': 'WATL targets are commonly built from layered wood so the axe can stick.',
    'kq011': 'A lane is designed so throwers and spectators stay out of the path of the axe.',
    'kq012': 'WATL includes more than one implement. Hatchet is one; there are bigger or different events too.',
    'kq013': 'Touch scoring counts the highest ring the axe touches, even if most of the blade sits in a lower ring.',
    'kq014': 'If regulation throws finish level, WATL often uses sudden-death extra throws to decide the winner.',
    'kq015': 'Walk up and pull the axe out carefully. Do not yank while someone else is about to throw.',
    'kq016': 'In this sport a hatchet is the smaller one-handed throwing axe, not a felling axe.',
    'kq017': 'The outer black ring is the lowest scoring ring on a WATL target.',
    'kq018': 'IATF majority-of-blade scoring cares where most of the blade sits, not just a tiny touch of a line.',
    'kq019': 'If you call a killshot or Clutch and miss that zone, you generally do not get the ordinary ring score instead.',
    'kq020': 'Spectators stay behind the marked area and never step into a live lane.',
    'kq021': 'Wood lets the blade bite and stay. Hard metal or stone targets bounce axes.',
    'kq022': 'Duals means two throwers competing throw-for-throw on the same game.',
    'kq023': 'Check the axe head, handle and your footing before you throw.',
    'kq024': 'Rugby union and rugby league do not start with the same number of players on the field.',
    'kq025': 'A try is grounding the ball in the in-goal. Use the rugby union point value before any conversion kick.',
    'kq026': 'The conversion is the kick after a try. It is worth fewer points than the try itself.',
    'kq027': 'A penalty goal and a drop goal share the same point value in union.',
    'kq028': 'Forwards wear the low shirt numbers. Know the usual number band for the pack.',
    'kq029': 'The scrum-half is the link from scrum and ruck to the backs and has a traditional number.',
    'kq030': 'The fullback stands last in defence and last in the back-line numbering.',
    'kq031': 'A lineout restarts after the ball has gone into touch.',
    'kq032': 'A scrum is a set-piece restart after certain minor mistakes, not after a try.',
    'kq033': 'The fly-half / first five-eighth has a traditional number in the back line.',
    'kq034': 'New Zealand men union team has a famous nickname used worldwide.',
    'kq035': 'A knock-on is when the ball goes forward off the hand or arm toward the opponents dead-ball line.',
    'kq036': 'Offside at a ruck is about staying behind the hindmost feet until you are onside again.',
    'kq037': 'A penalty try is given when a try would probably have been scored but for foul play.',
    'kq038': 'The front row is the three players who bind at the front of the scrum.',
    'kq039': 'League split from union long ago. One big difference is how many players and how play restarts.',
    'kq040': 'The conversion is taken in line with where the try was scored, not always in front of the posts.',
    'kq041': 'The haka is a Maori ceremonial dance performed by New Zealand teams before many test matches.',
    'kq042': 'Advantage lets the non-offending team play on if they might get a better outcome than the whistle.',
    'kq043': 'A maul is when the ball carrier is held up and teammates bind on, ball off the ground.',
    'kq044': 'World Rugby is the international governing body for rugby union.',
    'kq045': 'A red card sends a player off for the rest of that match.',
    'kq046': 'The 22 is the line 22 metres from the try line, used for some restart and kicking laws.',
    'kq047': 'In NZ a vehicle is generally heavy once its GVM is over a set kilogram figure.',
    'kq048': 'GVM is the maximum allowed loaded weight of that one vehicle as written on its plate.',
    'kq049': 'NZ medium goods vehicles sit in a GVM band between light vehicles and the heaviest trucks.',
    'kq050': 'The heavier NZ truck licence class coding is a numbered class, not a nickname.',
    'kq051': 'A semi-trailer hangs on the towing unit through a fifth-wheel coupling.',
    'kq052': 'A B-train is two trailers linked in a specific double combination used on NZ roads.',
    'kq053': 'A full trailer has its own front axle set and is towed by a drawbar, not sitting on a fifth wheel.',
    'kq054': 'Logging trucks carry stems in bunks with bolsters and often a pole or trailer behind.',
    'kq055': 'Class 2 on a NZ licence covers medium rigid trucks in a set GVM range.',
    'kq056': 'Class 5 is the top heavy combination licence for the heaviest truck-and-trailer work.',
    'kq057': 'HPMV is a NZ permit class for trucks that can run above standard mass or dimension on approved routes.',
    'kq058': 'Vehicle dimensions and mass on NZ roads are set in land-transport rules, not by guesswork.',
    'kq059': 'A curtainsider has flexible side curtains so freight can be loaded from the side.',
    'kq060': 'A tanker is built to carry liquids or gases in a tank body.',
    'kq061': 'Trailer-to-truck mass ratio matters so the combination can brake and steer safely.',
    'kq062': 'A rigid truck has the load space on the same chassis as the cab, no separate semi-trailer.',
    'kq063': 'Pole trailers carry long loads such as logs or pipes that need support at both ends.',
    'kq064': 'Stock trucks move live farm animals, with pens and ventilation built in.',
    'kq065': 'NZ heavy vehicles are generally right-hand drive; left-hand drive heavies are tightly limited.',
    'kq066': 'GCW / GCM is the maximum allowed weight of the whole combination, truck plus trailers.',
    'kq067': 'A tipper body hinges so the load can slide out when the ram lifts it.',
    'kq068': 'Underrun protection on a long log overhang is so other road users do not run under the load.',
    'kq069': 'This question is looking for the option that is not actually a NZ heavy-truck topic.',
    'kq070': 'Farm English has different words for a female chicken that lays eggs, a male, and a chick.',
    'kq071': 'A male chicken kept with hens has a common everyday name.',
    'kq072': 'A newly hatched chicken has its own everyday name.',
    'kq073': 'A young sheep, before it is a hogget or adult, has a specific name.',
})
