DETAILS.update({
    'mc040': 'Participation points to Maori having a real say in services, not only being consulted after decisions.',
    'mc041': 'Carl Rogers founded a major humanistic school. Name that approach, not CBT or behaviourism.',
    'mc042': 'Rogers taught three therapist attitudes that make a helping relationship work.',
    'mc043': 'CBT looks at how thinking, feeling and doing keep a problem going.',
    'mc044': 'Aaron Beck is a key founder of one modern talking therapy that works with thoughts.',
    'mc045': 'Gestalt work emphasises present-moment awareness and contact, not only childhood history.',
    'mc046': 'Narrative therapy often separates the person from the problem and looks at the stories that shape life.',
    'mc047': 'Systems ideas see a problem as part of a pattern between people, not only one person inner trait.',
    'mc048': 'Psychodynamic work draws on unconscious process and early relationship patterns.',
    'mc049': 'Solution-focused work looks toward preferred futures and what already works, more than long problem histories.',
    'mc050': 'Motivational interviewing is used when someone feels two ways about changing a behaviour.',
    'mc051': 'A pluralistic stance means more than one approach can help, chosen with the client.',
    'mc052': 'Unconditional positive regard is accepting the person without requiring them to earn your approval.',
    'mc053': 'Empathy is sensing the client world and checking you have it, not just feeling sorry for them.',
    'mc054': 'Congruence means the counsellor is genuine, not a fake professional mask.',
    'mc055': 'Humanistic therapies trust growth and the person capacity, given the right relationship conditions.',
    'mc056': 'Behavioural work focuses on what people do and how that is learned and reinforced.',
    'mc057': 'Attachment theory helps explain how early bonds shape later closeness and fear in relationships.',
    'mc058': 'Feminist and critical approaches look at power, gender and social context, not only private feelings.',
    'mc059': 'Existential themes include freedom, meaning, isolation and mortality.',
    'mc060': 'Transactional Analysis uses Parent, Adult and Child ego states and the idea of life scripts.',
    'mc061': 'Evidence-informed practice uses research plus client preference and counsellor skill, not research only.',
    'mc062': 'The empty-chair method is classically linked with Gestalt work.',
    'mc063': 'Homeostasis means a family system tending to stay in its usual balance, even if that balance is painful.',
    'mc064': 'A genogram maps family relationships and patterns across generations.',
    'mc065': 'Strengths-based work looks for resources and what the person can already do.',
    'mc066': 'Active listening is attending, reflecting and checking understanding, not planning your reply while they talk.',
    'mc067': 'A reflection of feeling names the emotion you sense, so the client can confirm or correct it.',
    'mc068': 'Open questions invite a fuller story, not just yes or no.',
    'mc069': 'Closed questions are handy when you need a clear fact or a yes/no check.',
    'mc070': 'A summary pulls together what has been said so you both know you are in the same place.',
    'mc071': 'Silence can give space to think. It is not always a mistake.',
    'mc072': 'Immediacy is talking about what is happening between you right now in the room.',
    'mc073': 'A skilful challenge names a discrepancy without attacking the person.',
    'mc074': 'A paraphrase restates the content in your words to check meaning.',
    'mc075': 'Rapport grows from respect, attention and a sense of safety, not from tricks.',
    'mc076': 'Goals work best when they are shared, clear enough to aim at, and open to review.',
    'mc077': 'Counsellor self-disclosure should be rare, short and for the client benefit, not the counsellor.',
    'mc078': 'Attending is the body-and-face side of listening: orientation, eye contact that fits culture, stillness.',
    'mc079': 'A process comment names the pattern of the talk, not only the topic.',
    'mc080': 'A good ending reviews what mattered, what is next, and how the person is leaving the room.',
    'mc081': 'Psychoeducation is sharing useful information in a way the client can use, not a lecture.',
    'mc082': 'Collaborative contracting sets how you will work together at the start.',
    'mc083': 'Validation means the feeling makes sense in context, not that every action is wise.',
    'mc084': 'When distress is high, grounding and safety come before deep exploration.',
    'mc085': 'Cultural humility is staying open and decentring your own culture as the only map.',
    'mc086': 'Supervision is not gossip and not personal therapy. It is how counsellors keep practice safe and skilful.',
    'mc087': 'NZAC expects practising members to have regular ongoing supervision.',
    'mc088': 'For Teina / Provisional members, the supervisor is expected to be a suitably experienced Tuakana / Full member.',
    'mc089': 'Supervision can cover ethics, stuck cases, self-care and skill, not only paperwork.',
    'mc090': 'Client identity still needs protection in supervision. Use care with names and details.',
    'mc091': 'School guidance counsellors are commonly expected to have their own supervision as well as school line management.',
    'mc092': 'A supervisor endorsement can be needed when someone applies to move membership level.',
    'mc093': 'A supervision contract should say how often you meet, confidentiality limits and what the work is for.',
    'mc094': 'Reflective practice means looking honestly at your own work, not only telling the story of the client.',
    'mc095': 'Feeling stuck with a case is a classic reason to take it to supervision promptly.',
    'mc096': 'Anxiety can be a normal feeling. It becomes a problem when it is too strong or lasts too long.',
    'mc097': 'Depression commonly involves persistent low mood and/or loss of interest, plus other changes that affect life.',
    'mc098': 'Counsellors do not prescribe. When medicine may help, the usual step is to support a GP or specialist review.',
    'mc099': 'Asking about suicide and self-harm risk is part of keeping people safe, not a trick diagnosis question.',
    'mc100': 'Trauma-informed practice emphasises safety, choice and not repeating harm in the way we work.',
    'mc101': 'Stigma can stop people seeking help. Naming it matters in how we talk about distress.',
    'mc102': 'A panic attack is a sudden surge of intense fear with strong body symptoms. It is time-limited, not just worry.',
    'mc103': 'Substance issues often need specialist support alongside talking work.',
    'mc104': 'Sleep, movement, people and routines are everyday supports for mental wellbeing.',
    'mc105': 'Grief is a natural response to loss. It has no single correct timetable.',
    'mc106': 'Counsellor self-care is an ethical issue because exhausted practitioners miss things and harm clients.',
    'mc107': 'Neurodiversity-affirming practice treats brains as different, not automatically broken.',
    'mc108': 'Possible psychosis is a reason to slow down, stay with safety and support a timely medical or mental-health review.',
    'mc109': 'Protective factors are the things that help a person stay safer and better: people, meaning, skills, supports.',
    'mc110': 'If someone is in clear, immediate danger of serious harm, safety can override ordinary confidentiality.',
    'mc111': 'School guidance counsellors support student wellbeing inside the school system, not only sport results or payroll.',
    'mc112': 'Guidance in NZ secondary schools is often expected to rest on a counselling qualification and NZAC membership pathway.',
    'mc113': 'Children are not small adults. Age, assent, caregivers and child-protection duties all shape the work.',
    'mc114': 'Child-protection concerns in Aotearoa may involve Oranga Tamariki and school safety processes.',
    'mc115': 'Confidentiality with minors is shared with safety and sometimes with caregivers, depending on age and risk.',
    'mc116': 'Adolescent work often needs attention to identity, peers, family and school, not only one symptom.',
    'mc117': 'A guidance role can include counselling, guidance about courses and working with the wider school system.',
    'mc118': 'Play and creative methods can help children show what they cannot yet say in adult talk.',
    'mc119': 'Child wellbeing in NZ is also shaped by housing, poverty, racism and school climate, not only home feelings.',
    'mc120': 'A course on children and adolescents looks at development and how to work with that age group in context.',
    'mc121': 'Bullying work often needs the young person, the school system and sometimes the peer group, not only one chat.',
    'mc122': 'Moving school is a known stress point. Guidance can help with belonging and practical settling.',
    'mc123': 'Family and couples work often uses systems ideas: patterns between people, not only one person traits.',
    'mc124': 'Triangulation is pulling a third person into a two-person conflict so the original pair never settles it.',
    'mc125': 'Circular questions ask about relationships from more than one person view, so patterns show up.',
    'mc126': 'Family in Aotearoa includes whanau and chosen family, not only a nuclear template.',
    'mc127': 'If there is violence or coercion, a joint couples session can make things more dangerous. Screen first.',
    'mc128': 'Structural family work looks at boundaries, hierarchy and who is in which subsystem.',
    'mc129': 'EFT for couples works with attachment bonds and the emotional cycle between partners.',
    'mc130': 'When parents have separated, the child needs stay in the centre and adult conflict is managed carefully.',
    'mc131': 'Joining means building enough alliance with family members that the work can actually start.',
    'mc132': 'A family-and-couples paper typically covers what family means, systems ideas and how sessions run.',
    'mc133': 'The Massey PGDip is an academic diploma. On its own it is not the same thing as being a qualified practising counsellor.',
    'mc134': 'NZ postgraduate diplomas are measured in credits. This course is a standard one-year full-time load.',
    'mc135': 'NZQF Level 8 sits at postgraduate diploma and bachelor-with-honours height, below a masters or doctorate.',
    'mc136': 'The diploma compulsory papers cover theory, culture, family/couples and work with young people.',
    'mc137': 'Moving from the diploma into the Master of Counselling is not automatic. Grades and selection apply.',
    'mc138': 'Critical reading means judging method, bias and whether the research fits Aotearoa, not just quoting the abstract.',
    'mc139': 'Guidance in organisations can mean helping people and systems, not only one-to-one therapy in a private room.',
    'mc140': 'Counselling here is shaped by Te Tiriti, NZAC ethics, local cultures and NZ law, not only imported US manuals.',
})
