DETAILS = {}
DETAILS.update({
    'hq001': 'Olympic riding is several sports, not one. This asks which event puts dressage, cross-country and show jumping together as phases of the same competition.',
    'hq002': 'Dressage names many collected movements. A piaffe is one of them. Think about the trot and whether the horse almost stays on the spot.',
    'hq003': 'A first show-jumping round is usually scored on penalties. Rails down and stop or run-out faults come before style marks; the clock often only splits a later jump-off.',
    'hq004': 'FEI is the international governing body for many horse sports. Expand each letter of the French name.',
    'hq005': 'Endurance is long-distance riding over marked trails. The usual measure is a distance, often tens to more than a hundred kilometres.',
    'hq006': 'Western pleasure is a judged rail class. The look judges want is a calm horse with easy, smooth gaits, not speed or cattle work.',
    'hq007': 'Vaulting happens on a cantering horse on a lunge. Think gymnastics or dance on horseback, not racing or jumping a course.',
    'hq008': 'Outdoor polo has a fixed number of mounted players on each team at once. Indoor or arena polo can use a different number.',
    'hq009': 'A furlong is an old racing distance still used on Thoroughbred tracks. It is a fraction of a mile, not a time or a fence type.',
    'hq010': 'Reining is a patterned Western class. Look for the flashy stops and spins that are its signature manoeuvres.',
    'hq011': 'In jumping, a combination is more than one fence ridden as a related set, with only one or two strides between the parts.',
    'hq012': 'Cross-country is the open-country phase of eventing. Fences are solid, and the horse needs speed, stamina and bravery.',
    'hq013': 'Most horses walk, trot and canter. Some gaited breeds add an extra four-beat running gait with its own name.',
    'hq014': 'Steeplechase is racing over obstacles, not a flat gallop on an empty track.',
    'hq015': 'Dressage marks run from 0 to 10. A 10 is the top of that scale.',
    'hq016': 'Barrel racing is a timed cloverleaf. Count how many barrels stand in the standard pattern.',
    'hq017': 'Cutting is a cattle class. The horse must peel one animal out of the herd and hold it there.',
    'hq018': 'Grand Prix is the top regular senior dressage level, with the hardest collected work.',
    'hq019': 'When two horses hit the line almost together, officials use a camera rather than guess from the stand.',
    'hq020': 'Horseball is a mounted ball sport with passing, shooting and picking the ball up off the ground.',
    'hq021': 'A chukka is a timed period of play. It belongs to one mounted team sport in particular.',
    'hq022': 'Hunt seat is an English style linked with jumping and the hunt field, not Western ranch classes.',
    'hq023': 'Combined driving is carriage sport with more than one phase, similar in idea to eventing.',
    'hq024': 'A refusal is when the horse stops or ducks out instead of jumping the fence in front of it.',
    'hq025': 'Para-equestrian dressage is the Paralympic form of dressage, with grades so riders of different abilities can compete fairly.',
    'hq026': 'The withers are a height and saddle-fit landmark at the top of the shoulder area, where the neck joins the back.',
    'hq027': 'The cannon is a long slim bone in the lower limb, below the knee or hock, not in the head or body.',
    'hq028': 'Look at the underside of the hoof. The frog is the softer V-shaped part that helps with grip and shock.',
    'hq029': 'This is about how horses digest plants and how their gut is built, not about whether they eat meat.',
    'hq030': 'Count the footfalls in one complete canter stride. Walk, trot and canter do not all have the same number of beats.',
    'hq031': 'A trot is a two-time diagonal gait. Count the beats in one stride.',
    'hq032': 'The poll is the point just behind the ears, where the head meets the neck.',
    'hq033': 'Match the horse joint to the similar human joint in the hind limb.',
    'hq034': 'The hock is the sharp-angled joint in the hind leg. Compare it with a human ankle, knee or wrist.',
    'hq035': 'Incisors sit at the front of the mouth. Think biting grass, not grinding it at the back.',
    'hq036': 'Adult horses have a full set of permanent teeth. The number is around thirty, give or take wolf teeth.',
    'hq037': 'Chestnuts are the small horny patches on the inner legs, leftovers from evolution, not a disease.',
    'hq038': 'A horse eyes sit on the sides of the head, so some areas right in front and right behind are hard to see.',
    'hq039': 'The coronary band is the rim of skin and tissue where the hoof wall grows down from the leg.',
    'hq040': 'Bay is a coat colour: body one shade, points another. It is not a breed name.',
    'hq041': 'Grey is a colour pattern that changes with age. Foals are usually born darker and lighten later.',
    'hq042': 'The gaskin is the muscular part of the hind leg above the hock.',
    'hq043': 'Horses almost never vomit. The reason is a one-way valve and the way the stomach and gullet meet.',
    'hq044': 'Dock is the solid tail-head, not the long hair that hangs from it.',
    'hq045': 'Near side is the side handlers usually approach and mount from in many English traditions.',
    'hq046': 'A hand is the old unit used for horse height. Convert it to centimetres or inches.',
    'hq047': 'Official height is taken at the highest point of the withers, not the ears or croup.',
    'hq048': 'The croup is the rump from the loin back to the tail-head.',
    'hq049': 'Flehmen is the lifted-lip face horses make when they smell something interesting.',
    'hq050': 'The cecum is a large hindgut pouch that helps ferment forage.',
    'hq051': 'A daily check is a welfare sweep: water, feed, droppings and whether the horse looks comfortable.',
    'hq052': 'Horses should be able to drink clean water through the day, not only now and then.',
    'hq053': 'Colic is not one disease. It is the name for abdominal pain and needs a vet if signs are serious.',
    'hq054': 'Hooves keep growing. Farriers usually visit on a weeks-to-a-couple-of-months rhythm, not once a year.',
    'hq055': 'Rugs are for weather and clipped horses that cannot keep warm enough on their own.',
    'hq056': 'Speak and move so the horse knows you are there before you step into a tight stall.',
    'hq057': 'Worming should follow a plan with faecal counts and a vet, not a random calendar guess.',
    'hq058': 'Floating is rasping sharp enamel points so the horse can chew comfortably.',
    'hq059': 'A tucked-up, dull horse that will not eat may be unwell. Think vet, not another hard school.',
    'hq060': 'Bedding should be clean and dry enough that the horse can lie down and the air stays reasonably dust-free.',
    'hq061': 'After hard work, walk and cool the horse before it stands hot in the stable.',
    'hq062': 'Vaccination timing belongs with a qualified horse-health professional, not a guess from a feed-store poster alone.',
    'hq063': 'Rain rot and mud fever often improve when skin is kept cleaner and drier, plus treatment if needed.',
    'hq064': 'Salt and minerals are often offered because forage and hard feed do not always cover what a horse loses.',
    'hq065': 'Treats are extras. Keep them small so they do not unbalance the diet or teach grabbing.',
    'hq066': 'A safety-release tie or similar idea means the horse is less likely to panic-break a solid fixture.',
    'hq067': 'Lameness can show as a head nod, shorter stride or reluctance to hold a gait.',
    'hq068': 'Turnout can help movement, minds and guts when the paddock and company are safe.',
    'hq069': 'Grain is a concentrate. It is measured and fed for work, not tipped out as a free-choice pile.',
    'hq070': 'Resting breathing is fairly slow. Know the usual breaths-per-minute band for a quiet horse.',
    'hq071': 'Body condition scoring is a hands-on way to judge fat cover, not just whether the coat shines.',
    'hq072': 'Fly masks shield eyes and sometimes ears from flies and UV.',
    'hq073': 'A cast horse is stuck against a wall. Get help and free it safely.',
    'hq074': 'Mouldy or dusty hay can irritate lungs and guts. Quality matters as much as quantity.',
    'hq075': 'This is rider head protection. A riding helmet is the usual safe choice whenever you ride.',
    'hq076': 'A snaffle works mainly by direct rein pressure, not by a long curb shank multiplying force.',
    'hq077': 'The girth (English) or cinch (Western) is the strap around the barrel that keeps the saddle in place.',
    'hq078': 'A martingale can limit extreme head-raising. Types differ, but that is the job.',
    'hq079': 'A curb bit uses leverage through a shank and usually a curb strap or chain under the chin.',
    'hq080': 'The pommel is the front rise of the saddle, in front of the rider.',
    'hq081': 'The cantle is the back of the saddle seat.',
    'hq082': 'The browband sits across the forehead and helps keep the bridle from sliding back.',
    'hq083': 'The throatlatch is the strap under the jaw throat that helps keep the bridle from coming off over the head.',
    'hq084': 'Stirrups should be the right length and sit so the rider foot is secure, not jammed or dangling.',
    'hq085': 'A numnah or pad sits under the saddle to protect the back and help the saddle sit cleanly.',
    'hq086': 'A hackamore is bitless. Control comes from the nose, chin and poll rather than a mouthpiece.',
    'hq087': 'English stirrup leathers hang from the saddle tree bars, not from the bit.',
    'hq088': 'A breastplate or breastcollar can stop the saddle sliding back, especially when going uphill or jumping.',
    'hq089': 'A flash is an extra strap off a cavesson noseband that can stabilize the bit.',
    'hq090': 'Clean leather lasts longer and is less likely to rub or snap.',
    'hq091': 'The Western horn is traditionally for dallying a rope.',
    'hq092': 'A girth done up too tight can pinch, restrict breathing and make the horse girthy.',
    'hq093': 'A running martingale attaches to the reins through rings, so it only acts when the head comes up.',
    'hq094': 'Bit width should match the horse mouth, not be a random size from the tack-room hook.',
    'hq095': 'A crupper runs from the saddle back to the tail to stop the saddle sliding forward.',
    'hq096': 'Thoroughbreds were bred first for the racetrack and athletic speed, not as heavy farm drafters.',
    'hq097': 'Arabians are famous for stamina, refined heads and often a dished profile.',
    'hq098': 'The Clydesdale is a heavy draught horse, known for size and leg feathering.',
    'hq099': 'Quarter Horses are built for short speed, cattle work and a powerful hind end.',
    'hq100': 'Friesians are often black with abundant mane and tail and a high-stepping presence.',
    'hq101': 'Shetland ponies come from the Shetland Islands and are small, strong and hardy.',
    'hq102': 'Warmbloods are often bred for sport, dressage and jumping, rather than as tiny pets.',
    'hq103': 'The Andalusian / PRE is the historic Iberian riding horse of Spain.',
    'hq104': 'Appaloosas are known for spotted coat patterns.',
})
